import { GoogleGenAI } from "@google/genai";
import { type Settings } from './settings';

function getAiClient(apiKey: string): GoogleGenAI {
  if (!apiKey) {
    throw new Error("Cloud Provider API Key is not configured.");
  }
  return new GoogleGenAI({ apiKey });
}

async function generateWithGemini(prompt: string, apiKey: string): Promise<string> {
    const ai = getAiClient(apiKey);
    try {
        const response = await ai.models.generateImages({
            // FIX: Updated model to recommended version from guidelines.
            model: 'imagen-4.0-generate-001',
            prompt: prompt,
            config: {
              numberOfImages: 1,
              outputMimeType: 'image/jpeg',
              aspectRatio: '1:1',
            },
        });

        if (response.generatedImages && response.generatedImages.length > 0) {
            const base64ImageBytes: string = response.generatedImages[0].image.imageBytes;
            return `data:image/jpeg;base64,${base64ImageBytes}`;
        } else {
            throw new Error("No images were generated by the API.");
        }
    } catch(error) {
        console.error("Error generating image with Gemini:", error);
        throw new Error(`Failed to generate image. ${error instanceof Error ? error.message : String(error)}`);
    }
}

async function generateWithOpenAI(prompt: string, settings: Settings, apiKey: string, signal?: AbortSignal): Promise<string> {
    if (!apiKey) {
        throw new Error("API Key not configured. An API key is required for OpenAI-compatible image generation.");
    }
     if (!settings.imageGenerationUrl) {
        throw new Error("OpenAI-Compatible Image Generation URL is not configured in Settings -> Image Generation.");
    }
    
    const apiUrl = settings.imageGenerationUrl; // User provides the full endpoint URL

    const body = {
        model: settings.imageGenerationModel,
        prompt: prompt,
        n: 1,
        size: "1024x1024",
        response_format: "b64_json",
    };

    try {
        const response = await fetch(apiUrl, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'Authorization': `Bearer ${apiKey}`,
            },
            body: JSON.stringify(body),
            signal, // Pass the signal here
        });

        if (!response.ok) {
            const errorBody = await response.text();
            throw new Error(`API Error (${response.status}) from ${apiUrl}: ${errorBody}`);
        }
        
        const data = await response.json();
        const b64_json = data.data?.[0]?.b64_json;
        
        if (!b64_json) {
            throw new Error("API response did not contain the expected 'b64_json' data.");
        }
        
        return `data:image/png;base64,${b64_json}`;

    } catch (error) {
         console.error("Error generating image with OpenAI-compatible API:", error);
         throw error;
    }
}

async function generateWithLocalApi(prompt: string, settings: Settings, signal?: AbortSignal): Promise<string> {
    if (!settings.imageGenerationUrl) {
        throw new Error("Local Image Generation URL is not configured in Settings.");
    }

    const apiUrl = settings.imageGenerationUrl;

    // A standard, simple body for Stable Diffusion WebUI txt2img
    const body = {
        prompt: prompt,
        steps: 25,
        width: 1024,
        height: 1024,
    };

    try {
        const response = await fetch(apiUrl, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
            },
            body: JSON.stringify(body),
            signal, // Pass the signal here
        });

        if (!response.ok) {
            const errorBody = await response.text();
            throw new Error(`API Error (${response.status}) from ${apiUrl}: ${errorBody}`);
        }
        
        const data = await response.json();
        const imageB64 = data.images?.[0];
        
        if (!imageB64) {
            throw new Error("API response did not contain the expected 'images' data. Response format might be incorrect.");
        }
        
        // The response is pure base64, no prefix.
        return `data:image/png;base64,${imageB64}`;

    } catch (error) {
         console.error("Error generating image with Local API:", error);
         if (error instanceof TypeError) {
             throw new Error("Failed to connect to the local image generation server. Is it running and is CORS configured correctly?");
         }
         throw error;
    }
}


export async function generateImage(prompt: string, settings: Settings, signal?: AbortSignal): Promise<string> {
    const getApiKey = (settings: Settings): string => {
        if (settings.developerMode) {
            if (settings.imageGenerationProvider === 'openai') {
                return settings.dev_openAiApiKey;
            }
            return settings.dev_geminiApiKey;
        }
        return process.env.API_KEY || '';
    };
    const apiKey = getApiKey(settings);

    switch (settings.imageGenerationProvider) {
        case 'gemini':
            return generateWithGemini(prompt, apiKey); // Cannot pass signal to Gemini API directly today.
        case 'openai':
            return generateWithOpenAI(prompt, settings, apiKey, signal);
        case 'local':
            return generateWithLocalApi(prompt, settings, signal);
        case 'none':
            throw new Error("Image generation is disabled. Please select a provider in Settings -> Image Generation.");
        default:
             throw new Error(`Unknown image generation provider: ${settings.imageGenerationProvider}`);
    }
}
